

-- DOCUMENTACAO PARA VERSIONAMENTO ATRAVES DO GIT
-- E SALVAMENTO NO GITHUB

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DB_04017C_PROF_CEZAR;

-- ACESSANDO O BD CRIADO
USE DB_04017C_PROF_CEZAR;

-- CRIANDO A TABELA USUARIOS
CREATE TABLE TB_USUARIOS (
cpf VARCHAR(20) NOT NULL PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
idade INT NOT NULL
);

-- INSERINDO REGISTROS NA TABELA USUARIOS
INSERT INTO TB_USUARIOS (cpf, nome, idade) 
values ('123.456.789-00', 'CEZAR', 30),
('123.456.789-01', 'MARIA', 20);

-- CONSULTANDO INFORMAÇÕES NA TABELA USUARIO
SELECT * FROM TB_USUARIOS;
