
-- ACESSANDO O BD
USE DB_04017C_CEZAR_SILVA;

-- ELIMINANDO UMA TABELA PRODUTO SE JA EXISTIR
DROP TABLE IF EXISTS TB_PRODUTOS_AULA;

-- CRIANDO A TABELA PRODUTOS
CREATE TABLE TB_PRODUTOS_AULA (
	id_produto INT AUTO_INCREMENT PRIMARY KEY,
    nome_produto VARCHAR(100) NOT NULL,
    quantidade INT NOT NULL
);

-- INSERIR PELOS MENOS 4 REGISTROS
INSERT INTO TB_PRODUTOS_AULA (nome_produto, quantidade) 
VALUES ('TV', 100),
       ('VIDEO GAME', 45),
       ('LAPTOP', 12),
       ('TECLADO', 79);
 
-- RETORNO DA TABELA DE PRODUTOS
SELECT * FROM TB_PRODUTOS_AULA;  
       

-- ATUALIZAR AO MENOS 1 REGISTRO
UPDATE TB_PRODUTOS_AULA
SET nome_produto = 'TV SAMSUNG'
WHERE id_produto = 1;

-- EXCLUIR UM REGISTRO
DELETE FROM TB_PRODUTOS_AULA
WHERE id_produto = 2;



-- CONSULTANDO A BASE - TABELA APOS AS ALTERAÇÕES
SELECT * FROM TB_PRODUTOS_AULA;




