

-- ACESSAR BANCO DE DADOS
USE DB_04017C_CEZAR_SILVA;

-- CONSULTANDO A TABELA DE CONTATOS
SELECT * FROM TB_AGENDA_CONTATOS;

-- ATUALIZAR O EMAIL DE 1 CONTATO DA NOSSA AGENDA
UPDATE TB_AGENDA_CONTATOS
SET email = 'cezar.silva@email.com.br'
WHERE id_contato = 1;

-- ALTERANDO A INFORMAÇÃO DE VARIAS COLUNAS
UPDATE TB_AGENDA_CONTATOS
SET nome = 'Cezar Silva',
    email = 'cezar@email.com'
WHERE id_contato = 1;


-- COMANDO DELETE -  EXCLUIR REGISTROS DA TABELA
DELETE FROM TB_AGENDA_CONTATOS
WHERE id_contato = 1;

-- CONSULTANDO A TABELA APOS A EXCLUSAO
SELECT * FROM TB_AGENDA_CONTATOS;
SELECT * FROM TB_AGENDA_TELEFONES;

-- eliminando 1 registro da tabela telefone
DELETE FROM TB_AGENDA_TELEFONES
WHERE telefone = '(11) 978784545';


-- eliminando todos os registros da tabela telefone
DELETE FROM TB_AGENDA_TELEFONES;














