
-- ACESSANDO O BD
USE DB_04017C_CEZAR_SILVA;

-- DROPAR TABELAS SE EXISTEREM
DROP TABLE IF EXISTS TB_AGENDA_CONTATOS_V2;
DROP TABLE IF EXISTS TB_AGENDA_CONTATOS_V3;


-- CRIAR TABELAS COM ESTRUTURAS DE OUTRAS
CREATE TABLE TB_AGENDA_CONTATOS_V2 AS SELECT * FROM TB_AGENDA_CONTATOS;
CREATE TABLE TB_AGENDA_CONTATOS_V3 AS SELECT * FROM TB_AGENDA_CONTATOS;

-- ALTER TABLE -- INCLUIR CAMPO AUTO INCEEMNTE -V2
ALTER TABLE TB_AGENDA_CONTATOS_V2
ADD PRIMARY KEY (id_contato);

ALTER TABLE TB_AGENDA_CONTATOS_V2
MODIFY COLUMN id_contato INT NOT NULL AUTO_INCREMENT;


-- ALTER TABLE -- INCLUIR CAMPO AUTO INCEEMNTE -V3
ALTER TABLE TB_AGENDA_CONTATOS_V3
ADD PRIMARY KEY (id_contato);

ALTER TABLE TB_AGENDA_CONTATOS_V3
MODIFY COLUMN id_contato INT NOT NULL AUTO_INCREMENT;


-- CONSULTANDO INFORMAÇÕES NAS TABELAS
SELECT * FROM TB_AGENDA_CONTATOS_V2;
SELECT * FROM TB_AGENDA_CONTATOS_V3;


-- DELETE SEM WHERE PARA ELIMINAR TODOS OS REGISTROS DA TABELA
DELETE FROM TB_AGENDA_CONTATOS_V2;

-- CONSULTANDO INFORMAÇÕES NAS TABELAS
SELECT * FROM TB_AGENDA_CONTATOS_V2;



-- inserir contatos V2
INSERT INTO TB_AGENDA_CONTATOS_V2 (nome, email, id_grupo_contato) values
('Cezar', 'cezar@email.com', 1),
('Luiza', 'luiza@email.com', 2),
('Pedro', 'pedro@email.com', 3);

-- CONSULTANDO INFORMAÇÕES NAS TABELAS
SELECT * FROM TB_AGENDA_CONTATOS_V2;



-- ELIMINAR REGISTROS DA TABELA V3
TRUNCATE TABLE TB_AGENDA_CONTATOS_V3;

-- CONSULTANDO INFORMAÇÕES NAS TABELAS
SELECT * FROM TB_AGENDA_CONTATOS_V3;

-- inserir contatos NA V3
INSERT INTO TB_AGENDA_CONTATOS_V3 (nome, email, id_grupo_contato) values
('Cezar', 'cezar@email.com', 1),
('Luiza', 'luiza@email.com', 2),
('Pedro', 'pedro@email.com', 3);

-- CONSULTANDO INFORMAÇÕES NAS TABELAS
SELECT * FROM TB_AGENDA_CONTATOS_V3;











